### ISSUE TITLE
启动APDPlat_Web错误

### ISSUE THREAD

**Issue by taolive** [ysc/APDPlat#54]
java.lang.IllegalArgumentException: org.hibernate.hql.ast.QuerySyntaxException: IndexScheduleConfig is not mapped [select o from IndexScheduleConfig o  order by o.id desc]
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1201) ~[hibernate-entitymanager-3.6.3.Final.jar:3.6.3.Final]
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1147) ~[hibernate-entitymanager-3.6.3.Final.jar:3.6.3.Final]
    at org.hibernate.ejb.AbstractEntityManagerImpl.createQuery(AbstractEntityManagerImpl.java:275) ~[hibernate-entitymanager-3.6.3.Final.jar:3.6.3.Final]
    at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
    at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:366) ~[spring-orm-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at com.sun.proxy.$Proxy106.createQuery(Unknown Source) ~[na:na]
    at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:241) ~[spring-orm-3.2.3.RELEASE.jar:3.2.3.RELEASE]
    at com.sun.proxy.$Proxy106.createQuery(Unknown Source) ~[na:na]
    at org.apdplat.platform.dao.DaoSupport.queryData(DaoSupport.java:106) ~[APDPlat_Core-2.5.jar:na]
    at org.apdplat.platform.dao.DaoFacade.query(DaoFacade.java:143) ~[APDPlat_Core-2.5.jar:na]
    at org.apdplat.platform.dao.DaoFacade.query(DaoFacade.java:135) ~[APDPlat_Core-2.5.jar:na]
    at org.apdplat.platform.service.ServiceFacade.query(ServiceFacade.java:111) ~[APDPlat_Core-2.5.jar:na]

全文搜索了IndexScheduleConfig 信息，未找到对应的表映射，是缺少表还是什么？
数据库里也未找到类似的表，帮忙解答下，谢谢！

**Comment by 2getodd** [comment]
[INFO] Web overrides =  none
[INFO] jetty-9.3.8.v20160314
[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@19f497aa{/,file:///D:/APDPlat-master/APDPlat_Web/target/APDPlat_Web-2.6/,UNAVAILABLE}{D:\APDPlat-master\APDPlat_Web\target\APDPlat_Web-2.6.war}
java.lang.Exception: Timeout scanning annotations
