### ISSUE TITLE
InfoType is not mapped 

### ISSUE THREAD

**Issue by wangkaijavaee** [ysc/APDPlat#68]
java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: InfoType is not mapped [select o from InfoType o  order by o.id desc]
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1374)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1310)
	at org.hibernate.ejb.AbstractEntityManagerImpl.createQuery(AbstractEntityManagerImpl.java:294)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:344)
	at com.sun.proxy.$Proxy106.createQuery(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:291)
	at com.sun.proxy.$Proxy106.createQuery(Unknown Source)
	at org.apdplat.platform.dao.DaoSupport.queryData(DaoSupport.java:92)
	at org.apdplat.platform.dao.DaoFacade.query(DaoFacade.java:143)
	at org.apdplat.platform.dao.DaoFacade.query(DaoFacade.java:135)
	at org.apdplat.platform.service.ServiceFacade.query(ServiceFacade.java:111)
	at org.apdplat.platform.service.ServiceFacade$$FastClassBySpringCGLIB$$ff76978f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:640)
	at org.apdplat.platform.service.ServiceFacade$$EnhancerBySpringCGLIB$$6b7b22dc.query(<generated>)
	at org.apdplat.module.system.service.RegisterService.shouldRegister(RegisterService.java:85)
	at org.apdplat.module.system.service.RegisterService.onApplicationEvent(RegisterService.java:55)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:98)

**Comment by ysc** [comment]
use apache-tomcat-8.0.21
